### ISSUE TITLE
SyntaxError: invalid syntax : File "rnn.py", line 162

### ISSUE THREAD

**Issue by minikin** [valentin012/conspeech#1]
Just wondering how to run this python scripts.
While I tried to run python rnn.py

```
python rnn.py
  File "rnn.py", line 162
    vocab = word_freq.most_common(vocabulary_size - 1)
        ^
SyntaxError: invalid syntax
```

**Comment by valentin012** [comment]
Hi

I have fixed these bugs now. However, the rnn-script is there just for 
completeness but it is not used for the actual generation task. You 
should try to run the demo.py script instead.

% python demo.py
% python demo.py [class]               Example: python demo.py RY
% python demo.py [class] [lambda]      Example: python demo.py RY 0.25

Best,
Valentin

**Comment by minikin** [comment]
Thank you!

ps: in demo.py on line 38 you have a wrong path : "PATH_TO_DATA = 'convote_v1.1\data_stage_three'"
but shoud be be 'PATH_TO_DATA = 'convote_v1.1/data_stage_three''
